openapi: 3.0.3
info:
  title: Asset API
  version: 1.0.0
  description: API for health check and CRUD operations on assets

paths:
  /health:
    get:
      summary: Health check
      description: Returns 200 OK if the service is healthy
      responses:
        '200':
          description: Service is healthy

  /api/asset:
    post:
      summary: Create a new asset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Asset'
      responses:
        '201':
          description: Asset created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Asset'

  /api/asset/{id}:
    get:
      summary: Get an asset by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Asset found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Asset'
        '404':
          description: Asset not found

    put:
      summary: Update an asset by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Asset'
      responses:
        '200':
          description: Asset updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Asset'

    delete:
      summary: Delete an asset by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Asset deleted

components:
  schemas:
    Asset:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        source:
          type: string
      required:
        - id
        - name
        - source